name: CI
on:
  push:
    branches: [ content ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set Git identity
      run: |
        git config --global user.email "mbuffa@gmail.com"
        git config --global user.name "Maxime Buffa"
    - name: Checkout Zola
      run: curl -s -L https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        zola build
    - name: Push
      run: |
        cd $GITHUB_WORKSPACE
        git fetch -p
        git checkout gh-pages
        rm -rf config.toml content sass templates
        cp -R public/* .
        rm -rf public
        git add -f .
        git commit -m "New release"
        git push origin gh-pages